sudo: required
services:
    - docker

before_install:
    - docker build jangdonghyeon/node-ali-chatbot 


after_success:
    - docker build -t jangdonghyeon/ali-client ./client
    - docker build -t jangdonghyeon/ali-nginx ./nginx
    - docker build -t jangdonghyeon/ali-server  ./server


    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jangdonghyeon/ali-client
    - docker push jangdonghyeon/ali-nginx
    - docker push jangdonghyeon/ali-server

