sudo: required
services:
    - docker

before_install:
    - docker build -t jangdonghyeon/node-ali-chatbot -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jangdonghyeon/node-ali-chatbot npm run test -- --coverage

after_success:
    - docker build -t jangdonghyeon/node-ali-chatbot-client ./client
    - docker build -t jangdonghyeon/node-ali-chatbot-nginx ./nginx
    - docker build -t jangdonghyeon/node-ali-chatbot-server ./server


    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jangdonghyeon/node-ali-chatbot-client
    - docker push jangdonghyeon/node-ali-chatbot-nginx
    - docker push jangdonghyeon/node-ali-chatbot-server
